# .travis.yml
language: php
php:
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --dev --no-interaction
  - wget https://phar.phpunit.de/phpunit.phar
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar

script:
  - php phpunit.phar

after_success:
  - php coveralls.phar
